
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create #create update none
    properties:
      hibernate:
        # show_sql: true
        format_sql: true